#!/bin/sh
if ( ! command -v ifconfig  >/dev/null 2>&1; )  ; then
{
	if ( command -v apt-get >/dev/null 2>&1; )  ; then
	{
		sudo apt-get install net-tools -y
	}
	elif ( command -v apt >/dev/null 2>&1; )  ; then
  {
    sudo apt install net-tools -y
	}
	elif ( command -v dnf >/dev/null 2>&1; )  ; then
	{
    sudo dnf install net-tools -y
	}
	elif ( command -v yum >/dev/null 2>&1; )  ; then
	{
    sudo yum install net-tools -y
	}
	fi
}
fi

ifconfig | grep 'inet ' | grep -v 127.0.0.1 | awk '{ print $2 }'

