#!/usr/bin/env bash
#Create a function in ~/.bashrc:

  if [[ -z "$ORIG" ]]; then
    ORIG=$PS1
  fi
  TITLE="\[\e]2;$@\a\]"
  PS1=${ORIG}${TITLE}
}
#Then use your new command to set the terminal title. It works with spaces in the name too
# $ set-title my new tab title